# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: ${PROJECT_NAME:-document-ingestion}
services:
  pgvector-vector-db:
    hostname: db
    image: pgvector/pgvector:pg16
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
      POSTGRES_DB: ${PGVECTOR_DBNAME}
    ports:
      - "5432:5432"

  dataprep_microservice:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: intel/document-ingestion:1.2.0
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      PG_CONNECTION_STRING: ${PG_CONNECTION_STRING}
      INDEX_NAME: ${INDEX_NAME}
      TEI_ENDPOINT_URL: ${TEI_ENDPOINT_URL}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      CHUNK_SIZE: ${CHUNK_SIZE}
      CHUNK_OVERLAP: ${CHUNK_OVERLAP}
      BATCH_SIZE: ${BATCH_SIZE}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN:?error}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
      MINIO_HOST: ${MINIO_HOST:-minio-server}
      MINIO_API_PORT: ${MINIO_API_PORT:-9000}
      # Raise error if following required env vars is not set
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:?error}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:?error}
    ports:
      - "${DATAPREP_HOST_PORT:-8000}:8000"
    depends_on:
      - pgvector-vector-db
      - tei-embedding-service
      - minio-server

  tei-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    ports:
      - "${TEI_HOST_PORT:-6006}:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    command: --model-id ${EMBEDDING_MODEL_NAME} --auto-truncate

  minio-server:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - "${MINIO_API_HOST_PORT:-9000}:${MINIO_API_PORT:-9000}"
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
    volumes:
      - "${MINIO_MOUNT_PATH:-/mnt/miniodata}:/data"
    command: |
      server /data
      --address ":${MINIO_API_PORT:-9000}"
      --console-address ":${MINIO_CONSOLE_PORT:-9001}"

networks:
  default:
    driver: bridge
