apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Chatqna.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.Chatqna.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Chatqna.name }}
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        allowPrivilegeEscalation: false
      containers:
        - name: {{ .Values.Chatqna.name }}
          image: {{ .Values.Chatqna.image.repository }}:{{ .Values.Chatqna.image.tag }}
          imagePullPolicy: {{ .Values.Chatqna.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.Chatqna.service.port }}
          env:
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.no_proxy }},vllm-service.{{ .Release.Namespace }},text-generation-service.{{ .Release.Namespace }},ovms.{{ .Release.Namespace }},reranker.{{ .Release.Namespace }},tei-embedding-service.{{ .Release.Namespace }},ovms-embedding.{{ .Release.Namespace }}"
            - name: HTTP_PROXY
              value: {{ .Values.global.proxy.http_proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.global.proxy.https_proxy }}
            - name: HF_TOKEN
              value: {{ .Values.global.huggingface.apiToken }}
            - name: HUGGINGFACEHUB_API_TOKEN
              value: {{ .Values.global.huggingface.apiToken }}
            - name: LLM_MODEL
              value: {{ .Values.global.LLM_MODEL }}
            - name: EMBEDDING_MODEL
              value: {{ .Values.global.EMBEDDING_MODEL_NAME }}
            - name: INDEX_NAME
              value: {{ .Values.Chatqna.env.INDEX_NAME }}
            - name: HOME
              value: /home/appuser
            - name: EMBEDDING_ENDPOINT_URL
              value: {{- if .Values.global.teiEmbeddingService.enabled }}
                      http://tei-embedding-service.{{ .Release.Namespace }}:6006
                    {{- else }}
                      http://ovms-embedding.{{ .Release.Namespace }}:8400/v3             
                    {{- end }} 
            - name: RERANKER_ENDPOINT
              value: http://reranker.{{ .Release.Namespace }}:{{ .Values.reranker.service.port }}/rerank
            - name: PG_CONNECTION_STRING
              value: {{ .Values.Chatqna.env.PG_CONNECTION_STRING }}{{ .Values.global.POSTGRES_USER }}:{{ .Values.global.POSTGRES_PASSWORD }}@pgvector.{{ .Release.Namespace }}:{{ .Values.Chatqna.env.PORT_DB }}
            - name: OTLP_ENDPOINT
              value:  {{- if eq .Values.global.OTLP_ENDPOINT ""}} {{- else}}
                         {{ .Values.global.OTLP_ENDPOINT }}
                      {{- end }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value:  {{- if eq .Values.global.OTLP_ENDPOINT ""}} {{- else}}
                         {{ .Values.global.OTLP_ENDPOINT }}
                      {{- end }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value:  {{- if eq .Values.global.OTLP_ENDPOINT ""}} {{- else}}
                         {{ .Values.global.OTLP_ENDPOINT }}/v1/traces
                      {{- end }}
            - name: OTEL_SERVICE_NAME
              value:  {{ .Values.Chatqna.env.OTEL_SERVICE_NAME }}
            - name: OTEL_SERVICE_ENV
              value:  {{ .Values.Chatqna.env.OTEL_SERVICE_ENV }}
            - name: OTEL_METRICS_EXPORTER
              value:  {{ .Values.Chatqna.env.OTEL_METRICS_EXPORTER }}
            - name: OTEL_TRACES_EXPORTER
              value:  {{ .Values.Chatqna.env.OTEL_TRACES_EXPORTER }}
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value:  {{ .Values.Chatqna.env.OTEL_EXPORTER_OTLP_TRACES_PROTOCOL }}  
            - name: OTEL_SERVICE_VERSION
              value:  {{ .Values.Chatqna.env.OTEL_SERVICE_VERSION }}
            - name: REQUESTS_CA_BUNDLE
              value:  {{ .Values.Chatqna.env.REQUESTS_CA_BUNDLE }}
            - name: ENDPOINT_URL
              value: {{ if .Values.vllmService.enabled }}
                      {{ .Values.Chatqna.env.ENDPOINT_URL }}.{{ .Release.Namespace }}:{{ .Values.vllmService.service.port }}/v1
                    {{ else if .Values.tgiService.enabled  }}
                     {{ .Values.Chatqna.env.ENDPOINT_URL }}.{{ .Release.Namespace }}:{{ .Values.tgiService.service.port }}/v1
                    {{ else if or .Values.ovmsService.enabled .Values.global.gpu.enabled }}
                      {{ .Values.Chatqna.env.ENDPOINT_URL }}.{{ .Release.Namespace }}:{{ .Values.ovmsService.service.port }}/v3
                    {{ end }}
            - name: FETCH_K
              value: "10"
            - name: SEED
              value: "{{ .Values.Chatqna.env.SEED }}"
          securityContext:
            allowPrivilegeEscalation: false
          {{- if .Values.global.OTLP_ENDPOINT }}
          volumeMounts:
            - name: ca-certificates
              mountPath: /usr/local/share/ca-certificates
            - name: ssl-certs
              mountPath: /etc/ssl/certs
          {{ end}}
      {{- if .Values.global.OTLP_ENDPOINT }}
      volumes:
        - name: ca-certificates
          hostPath:
            path: /usr/local/share/ca-certificates
            type: Directory
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
            type: Directory
      {{ end}}