# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: vlminference
description: A Helm chart for deploying the VLM Inference Microservice
type: application
version: 0.1.0
