apiVersion: v2
name: chat-question-and-answer-core
description: A Helm chart for deploying chatqna-core and its UI
version: 1.2.1
appVersion: "1.0"
dependencies:
  - name: chatqna-ui
    version: 0.1.0
    repository: "file://common/chatqna"
