apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egai-minio-pvc
  annotations:
    helm.sh/resource-policy: {{ .Values.global.pvc_policy }}  # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.egai_minio_pvc.size }}
