# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: mr-minio
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "minio-port"
      port: 8000
  selector:
    app: mr-minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mr-minio
  name: deployment-mr-minio
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-minio
  template:
    metadata:
      labels:
        app: mr-minio
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
        - name: mr-minio
          env:
            - name: MINIO_ACCESS_KEY
              value: "{{ .Values.env.MINIO_ACCESS_KEY }}"
            - name: MINIO_SECRET_KEY
              value: "{{ .Values.env.MINIO_SECRET_KEY }}"
          image: minio/minio:RELEASE.2020-12-12T08-39-07Z
          command: ['minio', 'server', '--address', ':8000', '--certs-dir', '/certs', '/data']
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: {{ .Values.volumes.minio_data.name }}
              mountPath: {{ .Values.volumes.minio_data.location }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.volumes.minio_data.name }}
          hostPath:
            path: {{ .Values.volumes.minio_data.hostpath }}
