namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: Always
storageClassName: manual
env:
  LOG_LEVEL: "INFO"
  CLASSIFICATION_DEVICE: "CPU"
  REST_SERVER_PORT: "8080"
  DETECTION_DEVICE: "CPU"
  ENABLE_RTSP: "true"
  APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC: "false"
  GST_DEBUG: "1"
  HTTPS: "false"
  RTSP_PORT: "8554"
  http_proxy: 
  https_proxy: 
  no_proxy: "eshqaservicelayer.intel.com,intel.com,.intel.com,localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,192.168.49.2"
privileged_access_required: false
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
config: 
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
    ext:
      rest_api_port: "30007"
      rtsp_output_port: "30025"
